
import json
import random

# Emojis & Symbols
status_emojis = ["✅", "⚠️", "❌", "🔄", "💤", "🔥", "🚀", "🛑"]
flags = ["🇹🇼", "🇯🇵", "🇺🇸", "🇬🇧", "🇩🇪", "🇫🇷", "🇰🇷", "🇨🇳", "🇻🇳", "🇹🇭"]
tech_emojis = ["🐍", "☕", "🦀", "🐘", "🐹", "🐧", "⚛️", "🐋", "📦", "🔧"]
misc_emojis = ["🎉", "💡", "🎨", "🎵", "🎮", "📚", "📷", "🍕", "🚗", "🏠"]

# Data Generators
def gen_server_name():
    prefix = random.choice(["Alpha", "Beta", "Gamma", "Delta", "Omega", "Prime", "Core", "Node"])
    suffix = random.randint(1, 99)
    flag = random.choice(flags)
    return f"{flag} {prefix}-{suffix:02d}"

def gen_status():
    return random.choice(["Running ✅", "Warning ⚠️", "Error ❌", "Deploying 🚀", "Maintenance 🔧"])

def gen_load():
    val = random.randint(0, 100)
    bar = "█" * (val // 10) + "░" * (10 - val // 10)
    return f"{val}% {bar}"

def gen_desc():
    actions = ["Optimizing", "Compiling", "Rendering", "Serving", "Backing up", "Scanning"]
    obj = ["database", "assets", "frontend", "backend", "logs", "cache"]
    emoji = random.choice(misc_emojis)
    return f"{emoji} {random.choice(actions)} {random.choice(obj)}"

# Generate Rows
rows = []
for i in range(25):
    rows.append({
        "ID": f"#{i+1000}",
        "Server": gen_server_name(),
        "Region": random.choice(flags) + " Region " + str(random.randint(1, 5)),
        "Status": gen_status(),
        "Load": gen_load(),
        "Task": gen_desc(),
        "Uptime": f"{random.randint(1, 100)}d {random.randint(0, 23)}h"
    })

data = {
    "headers": ["ID", "Server", "Region", "Status", "Load", "Task", "Uptime"],
    "rows": [list(r.values()) for r in rows],
    "title": "🖥️ Server Monitor Dashboard 2026",
    "footer": "Generated by Zeble Test Script • 📊 Live Data"
}

with open("rich_test_data.json", "w", encoding="utf-8") as f:
    json.dump(data, f, ensure_ascii=False, indent=2)

print("✅ Generated rich_test_data.json with 25 rows")
